### ISSUE TITLE
This only works on your computer!

### ISSUE THREAD

**Issue by callumacrae** [dareko/ansible-oracle-client#1] opened 2014-08-09 16:22 UTC
https://github.com/dareko/ansible-oracle-client/blob/master/tasks/main.yml#L5

You're doing it wrong :smile:

**Comment by aguynamedryan** [comment] 2014-08-28 22:49
I've addressed this, and other things, in #2

**Comment by dareko** [comment] 2014-12-30 13:08
@aguynamedryan, thank you for the updates. I've merged them and they are now published on galaxy.ansible.com.

@callumacrae, the issue is fixed now.

**Closed as completed by dareko** 2014-12-30 13:08 UTC
